#List of object files without path
_LINKOBJ = sha2.o

SRCDIR = .
OBJDIR = $(SRCDIR)/obj
CPPFLAGS = -Wall -I. -D_DEBUG=$(DEBUG)
STATIC_LIB = libSHA2.a
USEROPTIM = 

all: all_lib

include ../MakefileLibCommon

build_deps:
	#no dependencies

clean_deps:
	#no dependencies
