/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_vhf_pathtransform_PathTransform_Path */

#ifndef _Included_de_vhf_pathtransform_PathTransform_Path
#define _Included_de_vhf_pathtransform_PathTransform_Path
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_vhf_pathtransform_PathTransform_Path
 * Method:    createPath
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_de_vhf_pathtransform_PathTransform_00024Path_createPath
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_vhf_pathtransform_PathTransform_Path
 * Method:    deletePath
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_vhf_pathtransform_PathTransform_00024Path_deletePath
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_vhf_pathtransform_PathTransform_Path
 * Method:    pushBack
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_de_vhf_pathtransform_PathTransform_00024Path_pushBack
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     de_vhf_pathtransform_PathTransform_Path
 * Method:    getPointPtr
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_vhf_pathtransform_PathTransform_00024Path_getPointPtr
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     de_vhf_pathtransform_PathTransform_Path
 * Method:    getPointX
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_vhf_pathtransform_PathTransform_00024Path_getPointX
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_vhf_pathtransform_PathTransform_Path
 * Method:    getPointY
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_vhf_pathtransform_PathTransform_00024Path_getPointY
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_vhf_pathtransform_PathTransform_Path
 * Method:    getPointZ
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_vhf_pathtransform_PathTransform_00024Path_getPointZ
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_vhf_pathtransform_PathTransform_Path
 * Method:    getPointCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_vhf_pathtransform_PathTransform_00024Path_getPointCount
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
