/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_vhf_pathtransform_PathTransform */

#ifndef _Included_de_vhf_pathtransform_PathTransform
#define _Included_de_vhf_pathtransform_PathTransform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_vhf_pathtransform_PathTransform
 * Method:    createPathTransform
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_de_vhf_pathtransform_PathTransform_createPathTransform
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_vhf_pathtransform_PathTransform
 * Method:    printPathTransform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_vhf_pathtransform_PathTransform_printPathTransform
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_vhf_pathtransform_PathTransform
 * Method:    deletePathTransform
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_vhf_pathtransform_PathTransform_deletePathTransform
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_vhf_pathtransform_PathTransform
 * Method:    transformInPlace
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_vhf_pathtransform_PathTransform_transformInPlace
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_vhf_pathtransform_PathTransform
 * Method:    transform
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_vhf_pathtransform_PathTransform_transform
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
